services:
  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ~/.cache/pypoetry:/root/.cache/pypoetry
    environment:
      - DJANGO_ENV=development
    depends_on:
      - mongo

  mongo:
    image: mongo:8.0-rc
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express:1-20-alpine3.19
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      ME_CONFIG_BASICAUTH: false



volumes:
  mongo-data: